doorbell:
  module: doorbell
  class: Doorbell

garage_door_timeout:
  module: timeout
  class: Timeout
  global_dependencies:
    - common.base_app
    - common.validation
  trigger:
    entity_id: cover.garage_door
    state: 'open'
  reset_when:
    - entity_id: binary_sensor.garage_motion_sensor_1
    - entity_id: binary_sensor.garage_motion_sensor_2
  duration: 30
  on_timeout:
    domain: cover
    service: close_cover
    service_data:
      entity_id: cover.garage_door


# dependencies:
#   - people
#   - notifiers
#   - mqtt_notifier
#   - ios_notifier
#   - fcm_notifier
# entity_id: lock.front_door
# state: unlocked
# service: lock/lock
# timeout: input_number.front_door_lock_timeout
# wait: 60
# delay_if:
#   entity_id: binary_sensor.front_door_sensor
#   state: 'on'
#   notify: SECURITY_LOCK_TIMEOUT_DELAY
#   acknowledge_id: front_door_delay_ack
# notify: SECURITY_LOCK_TIMEOUT