doorbell:
  module: security
  class: Doorbell
  global_dependencies:
    - common.base_app
    - common.validation
  dependencies:
    - notifiers
  doorbell:
    entity_id: switch.doorbell
#
#unlock:
#  module: security
#  class: DoorLock
#  global_dependencies:
#    - common.base_app
#    - common.validation
#  dependencies:
#    - notifiers
#  people:
#    - person.teagan
#    - person.alan
#    - person.grace
#    - device_tracker.care
#  lock: lock.front_door

garage_door_timeout:
  module: timeout
  class: Timeout
  global_dependencies:
    - common.base_app
    - common.validation
  dependencies:
    - notifiers
  trigger:
    entity_id: cover.garage_door
    state: 'open'
  reset_when:
    - entity_id: binary_sensor.garage_motion_sensor_1
      value: 'on'
    - entity_id: binary_sensor.garage_motion_sensor_2
      value: 'on'
  duration: 30
  on_timeout:
    domain: cover
    service: close_cover
    service_data:
      entity_id: cover.garage_door
  notify:
    notify_category: SECURITY_COVER_CLOSED_TIMEOUT
    response_entity_id: cover.garage_door
    replacers:
      entity_name: garage door

front_door_lock_timeout:
  module: timeout
  class: Timeout
  global_dependencies:
    - common.base_app
    - common.validation
  dependencies:
    - notifiers
  trigger:
    entity_id: lock.front_door
    state: 'unlocked'
  pause_when:
    - entity_id: binary_sensor.front_door_sensor
      value: 'on'
  duration: 5
  on_timeout:
    domain: lock
    service: lock
    service_data:
      entity_id: lock.front_door
  notify:
    notify_category: SECURITY_LOCK_TIMEOUT
    response_entity_id: lock.front_door
    replacers:
      entity_name: front door



# dependencies:
#   - people
#   - notifiers
#   - mqtt_notifier
#   - ios_notifier
#   - fcm_notifier
# entity_id: lock.front_door
# state: unlocked
# service: lock/lock
# timeout: input_number.front_door_lock_timeout
# wait: 60
# delay_if:
#   entity_id: binary_sensor.front_door_sensor
#   state: 'on'
#   notify: SECURITY_LOCK_TIMEOUT_DELAY
#   acknowledge_id: front_door_delay_ack
# notify: SECURITY_LOCK_TIMEOUT